version: '3'
services:
  bridge:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: senither/hypixel-discord-chat-bridge
    environment:
      SERVER_HOST: mc.hypixel.net
      SERVER_PORT: 25565
      MINECRAFT_USERNAME: derek1233alt@gmail.com
      MINECRAFT_PASSWORD: BigChungus69!
      MINECRAFT_LOBBY_HOLDER: lobbyHolder
      MINECRAFT_ACCOUNT_TYPE: microsoft
      DISCORD_TOKEN: OTgwNTg3NjkyMjQyOTE5NDQ1.GIxm8J.vGMtP0vkNs0YtKiBuIdJymL0o6IBQyos-pIOI8
      DISCORD_CHANNEL: 980580874091397190
      DISCORD_COMMAND_ROLE: 995459376104079410
      DISCORD_OWNER_ID: 253796217820151808
      MESSAGE_MODE: bot
      EXPRESS_ENABLED: false
      EXPRESS_PORT: 8880
      EXPRESS_AUTHORIZATION: authorizationHeaderString
